from pptx import Presentation

class PPTGenerationSkill:
    """根据结构化输入生成 PowerPoint 文件（纯执行 Skill）"""

    name = "ppt_generation"

    def run(self, title: str, slides: list, output_path: str):
        prs = Presentation()

        cover = prs.slides.add_slide(prs.slide_layouts[0])
        cover.shapes.title.text = title
        cover.placeholders[1].text = "Generated by Agent Skill"

        for slide in slides:
            s = prs.slides.add_slide(prs.slide_layouts[1])
            s.shapes.title.text = slide["title"]
            s.shapes.placeholders[1].text = "\n".join(slide["content"])

        prs.save(output_path)

        return {
            "status": "success",
            "file": output_path,
            "slide_count": len(slides) + 1
        }
