from typing import Optional, Dict, Any, List
from .base import Agent, Message

class WriterAgent(Agent):
    name = "Writer"

    def __init__(self, bus, min_sections: int = 3):
        super().__init__(bus)
        self.min_sections = min_sections
        self.collected_snippets: List[Dict[str, Any]] = []

    def receive(self, message: Message) -> Optional[Message]:
        if message.meta.get("target") not in (None, self.name):
            return None

        if message.content == "SEARCH_RESULTS":
            # Accumulate snippets
            self.collected_snippets.extend(message.meta.get("snippets", []))
            # Decide if we need more; simple heuristic: if less than min_sections, ask a question
            if len(self.collected_snippets) < self.min_sections:
                followup = "Give me more details on definitions and differences relevant to the task."
                return Message(role=self.name, content=followup, meta={"intent": "followup_question", "target": "Supervisor"})
            else:
                # Draft
                report = self._compose_report()
                return Message(role=self.name, content=report, meta={"intent": "draft", "is_final_candidate": True})
        else:
            # Treat as arbitrary note; store if snippets attached
            if "snippets" in message.meta:
                self.collected_snippets.extend(message.meta["snippets"])
            return None

    def _compose_report(self) -> str:
        # Group snippets by file for citations
        by_file: Dict[str, List[Dict[str, Any]]] = {}
        for s in self.collected_snippets:
            by_file.setdefault(s["file"], []).append(s)

        header = "# A2A Report\n\n"
        body_sections: List[str] = []
        body_sections.append("This report was collaboratively generated by **Researcher** and **Writer** agents using only a local knowledge base.\n")
        # Core sections
        topics = ["Overview", "Key Differences", "Practical Tips"]
        for t in topics:
            paragraph = f"## {t}\n"
            # Use snippets to support content
            chosen = self.collected_snippets[:]
            chosen.sort(key=lambda x: (x["file"], x["start_line"]))
            lines = []
            for sn in chosen[:3]:
                lines.append(sn["text"])
            paragraph += (lines and "\n".join(lines) or "Content not available.") + "\n"
            body_sections.append(paragraph)

        # Citations
        cites = ["\n## Citations\n"]
        for f, items in by_file.items():
            items.sort(key=lambda x: x["start_line"])
            ranges = [f"{i['start_line']}-{i['end_line']}" for i in items[:5]]
            cites.append(f"- **{f}**: lines " + ", ".join(ranges))
        if len(cites) == 1:
            cites.append("- (No citations found)")

        return header + "\n".join(body_sections) + "\n" + "\n".join(cites) + "\n"
